apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exadigit-simulation-server
  name: exadigit-simulation-server
  namespace: stf218-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exadigit-simulation-server
  template:
    metadata:
      name: main
      labels:
        app: exadigit-simulation-server
    spec:
      serviceAccountName: exadigit-simulation-server
      containers:
      - image: registry.apps.marble.ccs.ornl.gov/stf218-app/exadigit-simulation-server:latest
        name: main
        imagePullPolicy: Always
        env:
          - name: EXADIGIT_ROOT_PATH
            value: "/exadigit/api"
          - name: EXADIGIT_DEBUG_MODE
            value: "false"
          - name: EXADIGIT_JOB_IMAGE
            value: "registry.apps.marble.ccs.ornl.gov/stf218-app/exadigit-simulation-server-simulation-job:latest"
          - name: EXADIGIT_ALLOW_ORIGINS
            value: '[
                "http://localhost:8080",
                "https://obsidian.css.ornl.gov",
                "https://obsidian-stage.apps.marble.ccs.ornl.gov"
              ]'
        envFrom:
          - secretRef:
              name: prod-infra-envconfig-service-sens-creds
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 500Mi
  strategy:
    type: Recreate
---
kind: Service
apiVersion: v1
metadata:
  name: exadigit-simulation-server
  namespace: stf218-app
  labels:
    app: exadigit-simulation-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: exadigit-simulation-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: stf218-app
  name: "exadigit-simulation-server"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: stf218-app
  name: "exadigit-simulation-server"
rules:
- apiGroups: ["batch"]
  resources:
  - "jobs"
  verbs:
  - "create"
  - "list"
  - "get"
  - "patch"
  - "watch"
  - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: stf218-app
  name: "exadigit-simulation-server"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "exadigit-simulation-server"
subjects:
- kind: ServiceAccount
  name: "exadigit-simulation-server"
