[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "simulation_server"
version = "0.0.1"
requires-python = ">=3.9"
description = "ExaDigiT Simulation Server"
readme = "README.md"
# license = {file = "LICENSE.txt"}

dependencies = [
    "pydantic==2.11.9",
    "pydantic-settings==2.10.1",
    "loguru==0.7.3",
    "SQLAlchemy==2.0.43",
    "pydruid==0.6.9",
    "kafka-python==2.2.15",
    "python-snappy==0.7.3",
    "jsonpath-ng==1.7.0",
    "fastapi==0.116.2",
    "uvicorn==0.35.0",
    "sqlparse==0.5.3",
    "kubernetes==33.1.0",
    "elasticsearch==7.13.4",
    "elasticsearch-dbapi==0.2.11",
    "requests==2.32.5",
    "raps@{root:uri}/simulation_server/simulation/raps",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

# [project.scripts]
# spam-cli = "spam:main_cli"

# [project.entry-points."spam.magical"]
# tomatoes = "spam:main_tomatoes"

 